### ISSUE TITLE
Undefined array key "webChannel"

### ISSUE THREAD

**Issue by ghost** [JPinkney/TVMaze-PHP-API-Wrapper#23]
```
[2022-02-13 15:02:10] REMOVED.ERROR: Undefined array key "webChannel" {"exception":"[object] (ErrorException(code: 0): Undefined array key \"webChannel\" at /var/www/REMOVED/vendor/joshpinkney/tv-maze-php-api/TVMaze/TVShow.php:126)
[stacktrace]
#0 /var/www/REMOVED/vendor/joshpinkney/tv-maze-php-api/TVMaze/TVShow.php(126): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/REMOVED/vendor/joshpinkney/tv-maze-php-api/TVMaze/TVMaze.php(73): JPinkney\\TVMaze\\TVShow->__construct()
#2 /var/www/REMOVED/removed/processing/tv/TVMaze.php(299): JPinkney\\TVMaze\\TVMaze->singleSearchAkas()
"}
```

**Comment by ghost** [comment]
Still getting this
